## Currently only used for coverage reports

sudo: required
dist: trusty
language: rust
rust: stable

matrix:
  include:
    # parallel builds for tests
    - env: NAME=all_features
           RUST_BACKTRACE=full
      script: 
        - scripts/test_all_features.sh
      after_success:
        - scripts/run_kcov.sh

  allow_failures:
    - rust: nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh; fi

## All scripts are run above...
script:
  - fail

#after_success: scripts/run_kcov.sh
