[workspace]
members = ["crates/client", 
           "crates/native-tls",
           "crates/openssl",
           "crates/proto",
           "crates/resolver",
           "crates/rustls",
           "crates/https",
           "crates/server",
           "tests/compatibility-tests",
           "tests/integration-tests",
           "bin",
           "util"]

[patch.crates-io]
typed-headers = { git = "https://github.com/o01eg/typed-headers", branch = "update-dependencies" }
