# This is a Makefile for `cargo make`, to use it first istall cargo-make with `cargo install cargo-make`

[config]
skip_core_tasks = true

[config.modify_core_tasks]
# if true, all core tasks are set to private (default false)
private = true


## Feature profiles
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.fmt]
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.build]
command = "cargo"
args = ["build", "@@remove-empty(FEATURES)"]

[tasks.test]
command = "cargo"
args = ["test", "@@remove-empty(FEATURES)"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--lib", "--examples", "--tests", "--bins", "@@remove-empty(FEATURES)", "--", "-D", "warnings"]

[tasks.build-bench]
command = "cargo"
toolchain = "nightly"
args = ["bench", "--no-run"]

[tasks.all]
dependencies = ["build", "test", "clippy", "fmt"]

[tasks.default]
dependencies = ["all"]


## defined tasks
[tasks.no-default-features]
workspace = false
env = { FEATURES = "--no-default-features" }
run_task = { name = "all", fork = true }

[tasks.default-features]
workspace = false
env = { FEATURES = "" }
run_task = { name = "all", fork = true }

[tasks.all-features]
workspace = false
env = { FEATURES = "--all-features" }
run_task = { name = "all", fork = true }

[tasks.dns-over-rustls]
workspace = false
env = { FEATURES = "--features=dns-over-rustls", CARGO_MAKE_WORKSPACE_SKIP_MEMBERS = "crates/proto;crates/native-tls;crates/openssl;crates/rustls;crates/https;tests/compatibility-tests;util" }
run_task = { name = "all", fork = true }

[tasks.dns-over-native-tls]
workspace = false
env = { FEATURES = "--features dns-over-native-tls" }
run_task = { name = "all", fork = true }

[tasks.dns-over-openssl]
workspace = false
FEATURES = "--features dns-over-openssl"
run_task = { name = "all", fork = true }

[tasks.dns-dnssec-openssl]
workspace = false
FEATURES = "--features dnssec-openssl"
run_task = { name = "all", fork = true }

[tasks.dns-dnssec-ring]
workspace = false
FEATURES = "--features dnssec-ring"
run_task = { name = "all", fork = true }

[tasks.mdns]
workspace = false
FEATURES = "--features mdns"
run_task = { name = "all", fork = true }

[tasks.world]
dependencies = ["no-default-features", "default-features", "all-features", "dns-over-rustls", "dns-over-native-tls", "dns-over-openssl", "dns-dnssec-openssl", "dns-dnssec-openssl", "dns-dnssec-ring", "mdns"]