name: rust-linux

on:
  push:
    branches:
      - cargo-make-automation
  pull_request:
    branches:
      - cargo-make-automation

jobs:
  default-features:
    name: default features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: download and install cargo-make
      run: cargo make default-features

  no-default-features:
    name: no default features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: download and install cargo-make
      run: cargo make no-default-features