name: rust

on:
  push:
    branches:
      - cargo-make-automation
  pull_request:
    branches:
      - cargo-make-automation

jobs:
  default-features-matrix:
    name: default
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        feature: [default-features, no-default-features, all-features]
        feature: [all-features]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: cargo make
      run: cargo make ${{ matrix.feature }}

  exhaustive-features-matrix:
    name: exhaustive
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [dns-over-rustls, dns-over-https-rustls, dns-over-native-tls, dns-over-openssl, dnssec-openssl, dnssec-ring, mdns]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: cargo make
      run: cargo make ${{ matrix.feature }}

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: cargo make clippy
      run: cargo make clippy
